# https://docs.github.com/ja/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # npm
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    target-branch: 'develop'
    token: ${{ secrets.BOT_TOKEN }}
    schedule:
      interval: 'monthly'
      time: '09:00'
      # Use Japan Standard Time (UTC +09:00)
      timezone: 'Asia/Tokyo'
    reviewers:
      - 'hiro0218'
    open-pull-requests-limit: 10
