# https://docs.github.com/ja/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    target-branch: 'develop'
    schedule:
      interval: 'monthly'
      time: '09:00'
      # Use Japan Standard Time (UTC +09:00)
      timezone: 'Asia/Tokyo'
    reviewers:
      - 'hiro0218'
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: 'puppeteer'
        versions: ['5.x.x']
