/**
 * Copyright (c) HashiCorp, Inc.
 * SPDX-License-Identifier: MPL-2.0
 */

/**
 * Next.jsのバンドル解析結果を比較するスクリプト（コアロジック）
 * Pages RouterとApp Router（Next.js 13以降）の両方に対応
 *
 * 処理概要:
 * 1. 現在のブランチと比較対象ブランチのバンドル解析結果を読み込む
 * 2. グローバルバンドルサイズの変化を分析
 * 3. 追加されたページと変更されたページを検出
 * 4. 分析結果をMarkdown形式でレポート出力
 * 5. App RouterとPages Routerのページを区別して表示
 */

import { filesize as originalFilesize } from 'filesize'
import path from 'path'
import { getBuildOutputDirectory, getOptions, safeReadJSON, safeWriteFile } from '../utils.mjs'
import { DETAILS_GLOBAL_BUNDLE, renderDetailsPageChanges } from '../templates.mjs'

// Override default filesize options to display a non-breakable space as a spacer.
const filesize = (bytes, options) => {
  return originalFilesize(bytes, {
    spacer: ' ',
    ...options,
  })
}

// Threshold for trivial changes that can be ignored (< 0.01% change)
const TRIVIAL_CHANGE_THRESHOLD = 0.01

/**
 * バンドル比較レポートを生成してファイルに書き出す
 * @param {object} [params] - 実行パラメータ
 * @param {string} [params.cwd] - 実行ディレクトリ（デフォルト: process.cwd）
 * @param {object} [params.options] - package.jsonのnextBundleAnalysis設定
 * @returns {{ output: string, commentPath: string }} 出力本文とコメントファイルのパス
 */
export function runCompare({ cwd = process.cwd(), options = getOptions(cwd) } = {}) {
  const BUDGET = options.budget
  const BUDGET_PERCENT_INCREASE_RED = options.budgetPercentIncreaseRed
  const MINIMUM_CHANGE_THRESHOLD = options.minimumChangeThreshold
  const SHOW_DETAILS = options.showDetails === undefined ? true : options.showDetails
  const BUILD_OUTPUT_DIRECTORY = getBuildOutputDirectory(options)
  const PACKAGE_NAME = options.name
  const SKIP_COMMENT_IF_EMPTY = options.skipCommentIfEmpty

  // import the current and base branch bundle stats
  const currentBundlePath = path.join(
    cwd,
    BUILD_OUTPUT_DIRECTORY,
    'analyze/__bundle_analysis.json'
  )
  const currentBundle = safeReadJSON(currentBundlePath)

  if (!currentBundle) {
    throw new Error(`Current bundle analysis not found at ${currentBundlePath}`)
  }

  const baseBundlePath = path.join(
    cwd,
    BUILD_OUTPUT_DIRECTORY,
    'analyze/base/bundle/__bundle_analysis.json'
  )
  const baseBundle = safeReadJSON(baseBundlePath) || {}
  const hasBaseBundle = baseBundle !== null && Object.keys(baseBundle).length > 0

  if (!hasBaseBundle) {
    console.log('No base bundle analysis found or invalid format. Running in single-bundle mode.')
  }

  const output = buildReport({
    currentBundle,
    baseBundle,
    hasBaseBundle,
    packageName: PACKAGE_NAME,
    showDetails: SHOW_DETAILS,
    budget: BUDGET,
    budgetPercentIncreaseRed: BUDGET_PERCENT_INCREASE_RED,
    minimumChangeThreshold: MINIMUM_CHANGE_THRESHOLD,
    skipCommentIfEmpty: SKIP_COMMENT_IF_EMPTY,
  })

  const commentPath = path.join(
    cwd,
    BUILD_OUTPUT_DIRECTORY,
    'analyze/__bundle_analysis_comment.txt'
  )
  safeWriteFile(commentPath, output.trim())

  return { output, commentPath }
}

/**
 * バンドル比較レポート本文を生成する
 * @param {object} params - レポート生成パラメータ
 * @param {object} params.currentBundle - 現在のバンドル解析データ
 * @param {object} params.baseBundle - 比較対象のバンドル解析データ
 * @param {boolean} params.hasBaseBundle - 比較対象の有無
 * @param {string} params.packageName - パッケージ名
 * @param {boolean} params.showDetails - 詳細セクション表示フラグ
 * @param {number} [params.budget] - バジェット（バイト）
 * @param {number} params.budgetPercentIncreaseRed - 赤判定の増加率
 * @param {number} [params.minimumChangeThreshold] - 最小変化しきい値（バイト）
 * @param {boolean} params.skipCommentIfEmpty - 変化無し時の空コメント化
 * @returns {string} Markdown本文
 */
export function buildReport({
  currentBundle,
  baseBundle,
  hasBaseBundle,
  packageName,
  showDetails,
  budget,
  budgetPercentIncreaseRed,
  minimumChangeThreshold,
  skipCommentIfEmpty,
}) {
  let output = `## 📦 Next.js Bundle Analysis for ${packageName}

This analysis was generated by the [Next.js Bundle Analysis action](https://github.com/hashicorp/nextjs-bundle-analysis). 🤖

`

  const globalBundleCurrent = currentBundle.__global || { gzip: 0, raw: 0 }
  const globalBundleBase = hasBaseBundle && baseBundle.__global
    ? baseBundle.__global
    : { gzip: 0, raw: 0 }

  const currentPages = { ...currentBundle }
  const basePages = { ...baseBundle }
  delete currentPages.__global
  delete basePages.__global

  const globalGzipDiff = globalBundleCurrent.gzip - globalBundleBase.gzip
  let globalBundleChanges = false

  if (
    hasBaseBundle &&
    globalGzipDiff !== 0 &&
    (minimumChangeThreshold === undefined ||
      Math.abs(globalGzipDiff) > minimumChangeThreshold)
  ) {
    globalBundleChanges = {
      page: 'global',
      raw: globalBundleCurrent.raw,
      gzip: globalBundleCurrent.gzip,
      gzipDiff: globalGzipDiff,
      isIncrease: Math.sign(globalGzipDiff) > 0,
    }
  }

  const changedPages = []
  const newPages = []

  for (let page in currentPages) {
    const currentStats = currentPages[page]
    const baseStats = hasBaseBundle ? (basePages[page] || null) : null

    if (!baseStats) {
      const displayPage = formatPagePath(page)
      newPages.push({ page: displayPage, originalPath: page, ...currentStats })
    } else if (currentStats.gzip !== baseStats.gzip) {
      const rawDiff = currentStats.raw - baseStats.raw
      const gzipDiff = currentStats.gzip - baseStats.gzip
      const isIncrease = Math.sign(gzipDiff) > 0

      if (
        minimumChangeThreshold === undefined ||
        Math.abs(gzipDiff) > minimumChangeThreshold
      ) {
        const displayPage = formatPagePath(page)
        changedPages.push({
          page: displayPage,
          originalPath: page,
          ...currentStats,
          rawDiff,
          gzipDiff,
          isIncrease,
        })
      }
    }
  }

  const ctx = {
    budget,
    budgetPercentIncreaseRed,
    hasBaseBundle,
    trivialChangeThreshold: TRIVIAL_CHANGE_THRESHOLD,
  }

  if (globalBundleChanges) {
    output += `### ${
      globalBundleChanges.isIncrease ? '⚠️' : '🎉'
    }  Global Bundle Size ${
      globalBundleChanges.isIncrease ? 'Increased' : 'Decreased'
    }

`
    output += markdownTable(globalBundleChanges, globalBundleCurrent, globalBundleBase, ctx)

    if (showDetails) {
      output += `\n${DETAILS_GLOBAL_BUNDLE}\n`
    }
  }

  if (newPages.length) {
    const plural = newPages.length > 1 ? 's' : ''
    output += `### New Page${plural} Added

The following page${plural} ${
      plural === 's' ? 'were' : 'was'
    } added to the bundle from the code in this PR:

`
    output += markdownTable(newPages, globalBundleCurrent, null, ctx) + '\n'
  }

  if (changedPages.length) {
    const plural = changedPages.length > 1 ? 's' : ''
    output += `### ${changedPages.length} Page${plural} Changed Size

The following page${plural} changed size from the code in this PR compared to its base branch:

`
    output += markdownTable(changedPages, globalBundleCurrent, globalBundleBase, ctx)

    if (showDetails) {
      output += `\n${renderDetailsPageChanges({
        budgetPercentIncreaseRed,
        budget: budget && globalBundleCurrent ? budget : null,
      })}\n`
    }
  }

  const hasNoChanges =
    (!hasBaseBundle || (!newPages.length && !changedPages.length && !globalBundleChanges))
  if (hasNoChanges) {
    if (!hasBaseBundle) {
      output += 'No base bundle found for comparison. Changes will be detected in the next commit.'
    } else {
      output += 'This PR introduced no changes to the JavaScript bundle! 🙌'
    }
  }

  output += `<!-- __NEXTJS_BUNDLE_${packageName} -->`

  if (hasNoChanges && skipCommentIfEmpty) {
    output = ''
  }

  return output
}

/**
 * Generates markdown table header for bundle analysis
 * @param {Object|null} globalBundleCurrent - Current global bundle data
 * @param {boolean} showBudget - Whether to show budget column
 * @param {object} ctx - 共有コンテキスト
 * @returns {string} Markdown table header
 */
function generateTableHeader(globalBundleCurrent, showBudget, ctx) {
  const columns = ['Page', 'Size (compressed)']

  if (globalBundleCurrent) {
    columns.push('First Load')
  }

  if (showBudget) {
    columns.push(`% of Budget (\`${filesize(ctx.budget)}\`)`)
  }

  const header = columns.join(' | ')
  const separator = columns.map(() => '---').join('|')

  return `${header} |\n|${separator}|`
}

/**
 * Calculates budget-related metrics for a page
 * @param {Object} pageData - Page bundle data
 * @param {Object|null} globalBundleCurrent - Current global bundle
 * @param {Object|null} globalBundleBase - Base global bundle
 * @param {boolean} showBudget - Whether budget calculation is needed
 * @param {object} ctx - 共有コンテキスト
 * @returns {Object} Budget metrics
 */
function calculateBudgetMetrics(pageData, globalBundleCurrent, globalBundleBase, showBudget, ctx) {
  const firstLoadSize = globalBundleCurrent
    ? pageData.gzip + globalBundleCurrent.gzip
    : 0

  const budgetPercentage = showBudget
    ? ((firstLoadSize / ctx.budget) * 100).toFixed(2)
    : 0

  const previousBudgetPercentage = ctx.hasBaseBundle && globalBundleBase && pageData.gzipDiff
    ? (((globalBundleBase.gzip + (pageData.gzip - pageData.gzipDiff)) / ctx.budget) * 100).toFixed(2)
    : 0

  const budgetChange = previousBudgetPercentage && ctx.hasBaseBundle
    ? (previousBudgetPercentage - budgetPercentage).toFixed(2)
    : 0

  return {
    firstLoadSize,
    budgetPercentage,
    previousBudgetPercentage,
    budgetChange
  }
}

/**
 * Generates a single table row for bundle data
 * @param {Object} pageData - Page bundle data
 * @param {Object|null} globalBundleCurrent - Current global bundle
 * @param {Object|null} globalBundleBase - Base global bundle
 * @param {boolean} showBudget - Whether to show budget column
 * @param {boolean} showBudgetDiff - Whether to show budget diff
 * @param {object} ctx - 共有コンテキスト
 * @returns {string} Markdown table row
 */
function generateTableRow(pageData, globalBundleCurrent, globalBundleBase, showBudget, showBudgetDiff, ctx) {
  const metrics = calculateBudgetMetrics(pageData, globalBundleCurrent, globalBundleBase, showBudget, ctx)

  return (
    `| \`${pageData.page}\`` +
    renderSize(pageData, showBudgetDiff, ctx) +
    renderFirstLoad(globalBundleCurrent, metrics.firstLoadSize) +
    renderBudgetPercentage(
      showBudget,
      metrics.budgetPercentage,
      metrics.previousBudgetPercentage,
      metrics.budgetChange,
      ctx
    ) +
    ' |\n'
  )
}

/**
 * Generates a complete markdown table for bundle analysis data
 * @param {Array|Object} _data - Bundle data (can be array or single object)
 * @param {Object|null} globalBundleCurrent - Current global bundle
 * @param {Object|null} globalBundleBase - Base global bundle for comparison
 * @param {object} ctx - 共有コンテキスト
 * @returns {string} Complete markdown table
 */
export function markdownTable(_data, globalBundleCurrent, globalBundleBase, ctx) {
  if (!_data || _data.length === 0) {
    return ''
  }

  const data = [].concat(_data)
  const showBudget = globalBundleCurrent && ctx.budget
  const showBudgetDiff = ctx.budget && !!globalBundleBase && ctx.hasBaseBundle

  const header = generateTableHeader(globalBundleCurrent, showBudget, ctx)
  const rows = data
    .map(pageData => generateTableRow(pageData, globalBundleCurrent, globalBundleBase, showBudget, showBudgetDiff, ctx))
    .join('')

  return `${header}\n${rows}`
}

/**
 * Renders the first load size column (global bundle + page bundle)
 * @param {Object|null} globalBundleCurrent - Current global bundle data
 * @param {number} firstLoadSize - Total first load size in bytes
 * @returns {string} Formatted table cell or empty string
 */
function renderFirstLoad(globalBundleCurrent, firstLoadSize) {
  if (!globalBundleCurrent) return ''
  return ` | ${filesize(firstLoadSize)}`
}

/**
 * Renders the size column with optional diff from base branch
 * @param {Object} d - Page bundle data
 * @param {number} d.gzip - Gzipped size in bytes
 * @param {number} [d.gzipDiff] - Size difference from base branch
 * @param {boolean} showBudgetDiff - Whether to show budget diff instead of size diff
 * @param {object} ctx - 共有コンテキスト
 * @returns {string} Formatted table cell with size and optional diff
 */
function renderSize(d, showBudgetDiff, ctx) {
  const gzd = d.gzipDiff
  const baseSize = d.gzip - gzd
  const percentChange = (gzd && baseSize !== 0) ? ((gzd / baseSize) * 100) : 0
  return ` | \`${filesize(d.gzip)}\`${
    gzd && !showBudgetDiff && ctx.hasBaseBundle
      ? ` _(${renderStatusIndicator(percentChange, ctx)}${filesize(gzd)})_`
      : ''
  }`
}

/**
 * Renders the budget percentage column with optional change indicator
 * @param {boolean} showBudget - Whether to show budget column
 * @param {string} budgetPercentage - Current budget percentage (formatted string)
 * @param {string} previousBudgetPercentage - Previous budget percentage (formatted string)
 * @param {string} budgetChange - Budget change percentage (formatted string)
 * @param {object} ctx - 共有コンテキスト
 * @returns {string} Formatted table cell or empty string
 */
function renderBudgetPercentage(
  showBudget,
  budgetPercentage,
  previousBudgetPercentage,
  budgetChange,
  ctx
) {
  if (!showBudget) return ''

  const budgetChangeText = ` _(${renderStatusIndicator(budgetChange, ctx)}${
    Math.abs(budgetChange) < ctx.trivialChangeThreshold
      ? '+/- <0.01%'
      : budgetChange + '%'
  })_`

  return ` | ${budgetPercentage}%${
    previousBudgetPercentage && ctx.hasBaseBundle ? budgetChangeText : ''
  }`
}

/**
 * Renders a colored emoji status indicator based on percentage change
 * @param {number} percentageChange - Percentage change (positive = increase, negative = decrease)
 * @param {object} ctx - 共有コンテキスト
 * @returns {string} Emoji indicator
 */
export function renderStatusIndicator(percentageChange, ctx) {
  let res = ''
  if (percentageChange > 0 && percentageChange < ctx.budgetPercentIncreaseRed) {
    res += '🟡 +'
  } else if (percentageChange >= ctx.budgetPercentIncreaseRed) {
    res += '🔴 +'
  } else if (Math.abs(percentageChange) < ctx.trivialChangeThreshold) {
    res += ''
  } else {
    res += '🟢 '
  }
  return res
}

/**
 * Formats page path for display, distinguishing between App Router and Pages Router
 * @param {string} pagePath - Original page path from bundle analysis
 * @returns {string} Formatted path
 */
export function formatPagePath(pagePath) {
  if (pagePath.startsWith('/_app/')) {
    return `[App] ${pagePath.substring(6)}`
  }

  if (pagePath.startsWith('/_shared/')) {
    return pagePath
  }

  return pagePath
}
