name: Auto Merge

on:
  pull_request:
    types: [labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is labeled with 'auto merge'
        run: |
          if [[ "${{ github.event.label.name }}" != "auto merge" ]]; then
            exit 1
          fi

      - name: Approve PR
        uses: hmarr/auto-approve-action@v4

      - name: Auto Merge
        uses: pascalgn/automerge-action@v0.16.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
