name: Auto Merge

on:
  pull_request:
    types: [labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check if PR is labeled with 'auto merge'
        run: |
          if [[ "${{ github.event.label.name }}" != "auto merge" ]]; then
            exit 1
          fi

      - name: Approve PR
        run: gh pr review "${{ github.event.pull_request.html_url }}" --approve

      - name: Auto Merge
        run: gh pr merge --merge --auto "${{ github.event.pull_request.html_url }}"
