name: Weekly NPM Update

on:
  schedule:
    - cron: '0 9 * * 1'
  push:
    branches:
      - develop
      - automated-npm-update
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  npm-update:
    env:
      pr_title: '[Automated] Update NPM dependencies'
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v5
        with:
          sparse-checkout: |
            package.json
            package-lock.json
            .node-version

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: '.node-version'
          cache: 'npm'

      - name: Run git pull --rebase
        run: git pull --rebase

      - name: Get changed files
        id: changed-files
        run: |
          current_branch=${GITHUB_REF#refs/heads/}
          default_branch=$(git remote show origin | grep 'HEAD branch' | cut -d' ' -f5)

          # 監視対象ファイルリスト
          files_to_check=("package.json" "package-lock.json")
          any_changed=false

          # 各ファイルの変更を検知
          for file in "${files_to_check[@]}"; do
            if git diff --name-only origin/$default_branch...$current_branch | grep "^$file$"; then
              echo "${file//-/_}_changed=true" >> $GITHUB_OUTPUT
              any_changed=true
            else
              echo "${file//-/_}_changed=false" >> $GITHUB_OUTPUT
            fi
          done

          # いずれかのファイルが変更された場合のフラグ
          echo "any_changed=$any_changed" >> $GITHUB_OUTPUT

      - name: Install dependencies
        if: steps.changed-files.outputs.any_changed == 'true'
        run: npm ci

      - name: Run nolyfill
        if: steps.changed-files.outputs.any_changed == 'true'
        run: npm run nolyfill

      - name: Update packages
        if: steps.changed-files.outputs.any_changed == 'true'
        run: npm update

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: ${{ steps.git-check.outputs.changes == 'true' }}
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.BOT_TOKEN }}
          base: develop
          add-paths: package-lock.json
          commit-message: Update npm dependencies
          title: ${{ env.pr_title }}
          body: 'Automated changes by GitHub Actions'
          branch: automated-npm-update
          delete-branch: true
