name: Auto Merge

on:
  pull_request:
    types: [labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    if: github.event.label.name == 'auto merge'
    runs-on: ubuntu-slim
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Approve PR
        run: gh pr review "${{ github.event.pull_request.html_url }}" --approve

      - name: Merge PR
        run: gh pr merge --merge "${{ github.event.pull_request.html_url }}"
