name: Pull Request Auto Assign
on:
  pull_request:
    types: [opened, reopened]
jobs:
  auto-assign:
    name: Assign author to PR
    runs-on: ubuntu-latest
    steps:
      - name: Assign author to PR
        uses: technote-space/assign-author@v1
