name: Summarize new issues

on:
  pull_request:
    types: [opened, reopened]

jobs:
  summary:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      models: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch PR diff
        id: fetch_diff
        run: |
          gh pr diff ${{ github.event.pull_request.number }} >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run AI inference
        id: inference
        uses: actions/ai-inference@v1
        with:
          prompt: |
            Summarize the following GitHub pull request in one paragraph:
            PR Diff: ${{ steps.fetch_diff.outputs }}

      - name: Comment with AI summary
        run: |
          gh pr comment $PR_NUMBER --body '${{ steps.inference.outputs.response }}'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          RESPONSE: ${{ steps.inference.outputs.response }}
