name: Summarize PR

on:
  pull_request:
    types: [opened, reopened]

jobs:
  summary:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      models: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch PR diff
        id: fetch_diff
        run: |
          echo "Base ref: ${{ github.event.pull_request.base.ref }}"
          echo "Head SHA: ${{ github.event.pull_request.head.sha }}"

          git fetch origin ${{ github.event.pull_request.base.ref }}
          CHANGED_FILES=$(git diff --name-status origin/${{ github.event.pull_request.base.ref }}...${{ github.event.pull_request.head.sha }})

          echo "--- Raw git diff output ---"
          echo "$CHANGED_FILES"
          echo "--- End Raw git diff output ---"

          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "files<<$EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run AI inference
        id: inference
        uses: actions/ai-inference@v1
        with:
          prompt: |
            以下のGitHubプルリクエストの差分（diff）を分析し、**必ず下記の指定フォーマットと指示に従って**、レビュー概要を日本語で生成してください。

            **指定フォーマットと指示:**
            ```
            ## PRレビュー概要

            ### 主な目的
            {diffの内容から推測される、この変更が目指している主なゴールや解決しようとしている課題を記述してください。例：バグ修正、機能追加、パフォーマンス改善、ドキュメント更新など。}

            ### 範囲
            {diffで変更が加えられたファイルの種類や、関連する機能・コンポーネントを記述してください。例：認証部分のバックエンドコード、設定ファイル、UIコンポーネント、ドキュメントファイルなど。}

            ### 影響範囲
            {この変更によって影響を受ける可能性のあるシステムの動作、ユーザー体験、他の機能、または開発ワークフローなどを記述してください。}
            ```

            **分析対象のPR Diff:**
            ${{ steps.fetch_diff.outputs.files }}

      - name: Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: ai-summary-comment
          message: ${{ steps.inference.outputs.response }}
